# Generated by Django 3.0.6 on 2020-06-10 14:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('snippets', '0004_auto_20200610_1449'),
    ]

    operations = [
        migrations.AlterField(
            model_name='snippet',
            name='tags',
            field=models.ManyToManyField(blank=True, null=True, related_name='snips', to='snippets.Tag'),
        ),
    ]
